alias: Změna jasu kostičkou
description: |-
  Změna jasu otáčením kostičky:
  Otočení doprava -> zvýšení jasu
  Otočení doprava -> snížení jasu
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/Kosticka
condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action in ['rotate_left','rotate_right'] }}"
  - condition: state
    entity_id: light.zarovicka
    state: "on"
action:
  - service: light.turn_on
    target:
      entity_id: light.zarovicka
    data_template:
      brightness_step: |
        {% if trigger.payload_json.action == 'rotate_left' %}
          -10
        {% elif trigger.payload_json.action == 'rotate_right'%}
          10
        {% endif %}
mode: single
